apiVersion: v2
name: homepage
description: A modern, fully static, fast, secure fully proxied, highly customizable application dashboard with integrations for over 100 services and translations into multiple languages.
type: application
version: 1.8.7
appVersion: "v2.0.0"
keywords:
  - homepage
  - dashboard
  - docker
  - kubernetes
  - services
home: https://github.com/gethomepage/homepage
sources:
  - https://github.com/gethomepage/homepage
maintainers:
  - name: UnknownIQ
icon: https://raw.githubusercontent.com/gethomepage/homepage/dev/public/mstile-310x310.png
annotations:
  artifacthub.io/changes: |
    - kind: changed
      breaking: true
      description: Update homepage to v2.0.0 (major release with new built-in auth system); add optional auth.yaml config support
