{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "searxng.fullname" . }}-secret
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secret.secretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
