{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "searxng.fullname" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "searxng.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.basicAuth }}
      basicAuth:
        password:
          name: {{ .Values.serviceMonitor.basicAuth.password.name }}
          key: {{ .Values.serviceMonitor.basicAuth.password.key }}
        username:
          name: {{ .Values.serviceMonitor.basicAuth.username.name }}
          key: {{ .Values.serviceMonitor.basicAuth.username.key }}
      {{- end }}
{{- end }}
