{{- if .Values.defrag.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "etcd.fullname" . }}-defrag
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
    app.kubernetes.io/component: defrag
spec:
  schedule: {{ .Values.defrag.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "etcd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: defrag
    spec:
      template:
        metadata:
          labels:
            {{- include "etcd.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: defrag
        spec:
          serviceAccountName: {{ include "etcd.serviceAccountName" . }}
          restartPolicy: OnFailure
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
          initContainers:
          - name: download-etcdctl
            image: busybox:1.37
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -ec
            - |
              ETCD_VER={{ .Values.image.tag | default .Chart.AppVersion }}
              DOWNLOAD_URL=https://github.com/etcd-io/etcd/releases/download
              echo "Downloading etcdctl ${ETCD_VER}..."
              wget -q ${DOWNLOAD_URL}/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -O /tmp/etcd.tar.gz
              tar xzf /tmp/etcd.tar.gz -C /tmp --strip-components=1
              cp /tmp/etcdctl /etcdctl-bin/etcdctl
              chmod +x /etcdctl-bin/etcdctl
              rm -rf /tmp/etcd*
              echo "etcdctl downloaded successfully"
            securityContext:
              runAsNonRoot: true
              runAsUser: 1001
              runAsGroup: 1001
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
            volumeMounts:
            - name: etcdctl-bin
              mountPath: /etcdctl-bin
          containers:
          - name: etcd-defrag
            image: alpine:3.21
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -ec
            - |
              echo "Starting etcd defragmentation..."

              {{- $fullname := include "etcd.fullname" . }}
              {{- $protocol := include "etcd.clientProtocol" . }}
              {{- if .Values.tls.enabled }}
              ETCDCTL_OPTS="--cacert=/tls/client/{{ .Values.tls.client.caFilename }} --cert=/tls/client/{{ .Values.tls.client.certFilename }} --key=/tls/client/{{ .Values.tls.client.keyFilename }}"
              {{- else }}
              ETCDCTL_OPTS=""
              {{- end }}

              {{- range $i := until (int .Values.replicaCount) }}
              echo "Defragmenting {{ $fullname }}-{{ $i }}..."
              ETCDCTL_API=3 /etcdctl-bin/etcdctl \
                --endpoints={{ $protocol }}://{{ $fullname }}-{{ $i }}.{{ $fullname }}-headless:{{ $.Values.service.clientPort }} \
                ${ETCDCTL_OPTS} \
                defrag --command-timeout=60s

              echo "Waiting 10 seconds before next member..."
              sleep 10
              {{- end }}

              echo "Defragmentation completed for all members!"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              readOnlyRootFilesystem: false
            resources:
              {{- toYaml .Values.defrag.resources | nindent 14 }}
            volumeMounts:
            - name: etcdctl-bin
              mountPath: /etcdctl-bin
              readOnly: true
            {{- if .Values.tls.enabled }}
            - name: tls-client
              mountPath: /tls/client
              readOnly: true
            {{- end }}
          volumes:
          - name: etcdctl-bin
            emptyDir: {}
          {{- if .Values.tls.enabled }}
          - name: tls-client
            secret:
              secretName: {{ .Values.tls.client.existingSecret | default (printf "%s-client-tls" (include "etcd.fullname" .)) }}
              defaultMode: 0400
          {{- end }}
{{- end }}
