{{- if and .Values.tls.enabled (not .Values.tls.client.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}-client-tls
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  # IMPORTANT: These are placeholder values.
  # In production, you MUST provide actual TLS certificates via:
  # 1. Using tls.client.existingSecret to reference an existing secret
  # 2. Using cert-manager to auto-generate certificates
  # 3. Manually creating the secret before installing this chart
  {{- .Values.tls.client.caFilename | required "tls.client.caFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual CA certificate
  {{- .Values.tls.client.certFilename | required "tls.client.certFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual client certificate
  {{- .Values.tls.client.keyFilename | required "tls.client.keyFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual client key
{{- end }}
{{- if and .Values.tls.enabled (not .Values.tls.peer.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}-peer-tls
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  # IMPORTANT: These are placeholder values.
  # In production, you MUST provide actual TLS certificates via:
  # 1. Using tls.peer.existingSecret to reference an existing secret
  # 2. Using cert-manager to auto-generate certificates
  # 3. Manually creating the secret before installing this chart
  {{- .Values.tls.peer.caFilename | required "tls.peer.caFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual CA certificate
  {{- .Values.tls.peer.certFilename | required "tls.peer.certFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual peer certificate
  {{- .Values.tls.peer.keyFilename | required "tls.peer.keyFilename is required when TLS is enabled" }}: |
    # Placeholder - Replace with actual peer key
{{- end }}
